# GitMesh Community Edition — Funding
# -----------------------------------
# Funding here is for GitMesh Community Edition (CE) only.
#
# It does NOT grant:
# - Any ownership or rights over the code
# - Any governance, roadmap, or decision-making influence
# - Any special commercial or support privileges
#
# Funders may be acknowledged publicly as supporters of GitMesh CE.
#
# For any commercial, enterprise, or GitMesh Enterprise Edition (EE)
# discussions, please contact:
#   CEO of Alveoli — rawx18.dev@gmail.com

github:
patreon:
open_collective:
ko_fi: gitmesh
tidelift:
community_bridge:
liberapay:
issuehunt:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - https://crowdfunding.lfx.linuxfoundation.org/projects/gitmesh-git-collaboration-network-for-oss
