#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Setting up Vibe Coding environment...${NC}\n"
echo -e "${YELLOW}Vibe coding is about speed and flow — but never at the cost of security or stability.${NC}"
echo -e "${YELLOW}Please vibe code responsibly: don't break existing features, and don't weaken security.${NC}\n"

# Create .vibe directory if it doesn't exist
if [ ! -d ".vibe" ]; then
    echo -e "${YELLOW}Creating .vibe directory for shared AI config...${NC}"
    mkdir -p .vibe
fi

# Create necessary subdirectories
mkdir -p .github
mkdir -p .cody
mkdir -p .continue

# Function to create symlink safely
create_symlink() {
    local source=$1
    local target=$2
    
    # Remove existing file/symlink if it exists
    if [ -e "$target" ] || [ -L "$target" ]; then
        echo -e "${YELLOW}Removing existing $target to refresh link...${NC}"
        rm -f "$target"
    fi
    
    # Create symlink
    ln -sf "$source" "$target"
    echo -e "${GREEN}✓ Linked:${NC} $target → $source"
}

echo -e "\n${BLUE}Creating symlinks for AI tooling configs...${NC}\n"

# Cursor IDE
create_symlink ".vibe/cursor-rules.md" ".cursorrules"

# Claude Code / Cline
create_symlink ".vibe/claude-context.md" ".clinerules"

# Windsurf IDE
create_symlink ".vibe/windsurf-rules.md" ".windsurfrules"

# Supermaven
create_symlink ".vibe/supermaven-rules.md" ".supermavenrules"

# Aider
create_symlink ".vibe/aider-config.md" ".aider.conf.yml"

# GitHub Copilot
create_symlink "../.vibe/copilot-instructions.md" ".github/copilot-instructions.yml"

# Sourcegraph Cody
create_symlink "../.vibe/cody-context.md" ".cody/context.md"

# Continue.dev
create_symlink "../.vibe/continue-config.md" ".continue/config.json"

# Gemini CLI
create_symlink ".vibe/gemini-config.md" ".geminiconfig"

# Create .symlinks documentation file
echo -e "\n${BLUE}Creating .symlinks documentation...${NC}"
cat > .symlinks << 'EOF'
# Vibe Coding Symlinks Reference
# This file is auto-generated by setup-vibe.sh
# DO NOT COMMIT - listed in .gitignore

========================================
ACTIVE SYMLINKS FOR AI CODING TOOLS
========================================

Root Directory Symlinks:
------------------------
.cursorrules          -> .vibe/cursor-rules.md          [Cursor IDE]
.clinerules           -> .vibe/claude-context.md        [Claude Code/Cline]
.windsurfrules        -> .vibe/windsurf-rules.md        [Windsurf IDE]
.supermavenrules      -> .vibe/supermaven-rules.md      [Supermaven]
.aider.conf.yml       -> .vibe/aider-config.md          [Aider]
.geminiconfig         -> .vibe/gemini-config.md         [Gemini CLI]

Subdirectory Symlinks:
---------------------
.github/copilot-instructions.yml  -> ../.vibe/copilot-instructions.md  [GitHub Copilot]
.cody/context.md                  -> ../.vibe/cody-context.md          [Sourcegraph Cody]
.continue/config.json             -> ../.vibe/continue-config.md       [Continue.dev]

========================================
TROUBLESHOOTING
========================================

Check if symlinks exist:
  ls -la | grep "^l"

Verify a specific symlink:
  readlink .cursorrules

Re-create all symlinks:
  ./setup-vibe.sh

Manual symlink creation:
  ln -sf .vibe/cursor-rules.md .cursorrules

========================================
HOW IT WORKS
========================================

1. Real configs live in .vibe/ (version controlled)
2. Symlinks created locally (NOT version controlled)
3. AI tools read from symlinks -> .vibe/ configs
4. Edit .vibe/ files, changes apply everywhere

========================================
Generated: $(date)
========================================
EOF

echo -e "${GREEN}✓ Created .symlinks reference file${NC}"

# Create .gitignore entry to ignore symlinks but keep .vibe/
if ! grep -q "# Vibe Coding Symlinks" .gitignore 2>/dev/null; then
    echo -e "\n${BLUE}Updating .gitignore for Vibe Coding symlinks...${NC}"
    cat >> .gitignore << 'EOF'

# Vibe Coding Symlinks (actual configs are in .vibe/)
.symlinks
.cursorrules
.clinerules
.windsurfrules
.supermavenrules
.aider.conf.yml
.geminiconfig
.github/copilot-instructions.yml
.cody/context.md
.continue/config.json
EOF
    echo -e "${GREEN}✓ .gitignore updated${NC}"
fi

echo -e "\n${GREEN}✨ Vibe Coding setup complete!${NC}"
echo -e "${BLUE}Your AI tools now read shared configurations from the .vibe/ directory.${NC}"
echo -e "${YELLOW}Edit files in .vibe/ to update behavior across all AI tools — and remember:${NC}"
echo -e "${YELLOW}vibe fast, but code responsibly: protect security, respect tests, and avoid breaking users.${NC}\n"

# List all created symlinks
echo -e "${BLUE}Created symlinks:${NC}"
ls -la | grep "^l" | grep -E "\.(cursorrules|clinerules|windsurfrules|supermavenrules|aider)" || echo "  (checking root directory)"
ls -la .github/ 2>/dev/null | grep "^l" || true
ls -la .cody/ 2>/dev/null | grep "^l" || true
ls -la .continue/ 2>/dev/null | grep "^l" || true

echo -e "\n${GREEN}Happy vibe coding — responsibly. ${NC}\n"

# Red color for warnings
echo -e "${RED}To remove all Vibe symlinks, run: ./remove-vibe.sh${NC}"